### ISSUE TITLE
Wrong redirect with WordPress in a sub subdirectory (apache)

### ISSUE THREAD

**Issue by christiaanstijnen** [level-level/ll-cookie-wall#1]
Verkeerde redirect met wordpress installatie in subdirectory (apache)

Wanneer je wordpress in een subdirectory installeert (www.domein.nl/wordpress-installatie/) dan stuurt de cookie plugin je terug naar www.domein.nl/cookie-wall ipv www.domein.nl/wordpress-installatie/cookie-wall.

**Comment by jmslbam** [comment]
Ok, het is niet erg dat directories niet geskipped worden, dus dan maar op de wp-admin ook een notice
