### ISSUE TITLE
Agree button wordt niet weergegeven.

### ISSUE THREAD

**Issue by christiaanstijnen** [level-level/ll-cookie-wall#2]
Als de cookie-wall wordt getriggerd is de agree button niet zichtbaar dus de cookie-wall kan niet weg geklikt worden.

Dit doet zich voor op dezelfde installatie van wordpress in een submap waarbij ik zelf de apache regel heb weggehaald om hem te laten functioneren. (https://github.com/level-level/ll-cookie-wall/issues/1)

**Comment by jmslbam** [comment]
Fixed
