### ISSUE TITLE
Disable Google Analytics Demographics & Interests in cookie wall

### ISSUE THREAD

**Issue by jphorn** [level-level/ll-cookie-wall#21]
Publishers who have Demographics and Interests (Remarketing) enabled in their Google Analytics profile will send an additional Doubleclick tracker in the Cookie Wall, which is against the Dutch law (since it allows for profiling). Fortunately Google allows disabling this tracker programmatically, instead of completely disabling this in your GA settings.

https://support.google.com/analytics/answer/2444872#trackingcode
> If you want to manually disable Advertising Reporting Features, you can modify your tracking code as described in the relevant sections below.

The specific code (which we have added to ll-cookie-wall on iCulture.nl) is:
`ga('set', 'displayFeaturesTask', null);`

This disables the Doubleclick tracking cookie for the cookie wall session, and allows the site owner to use the Remarketing feature after users accept the cookie statement.

**Comment by jmslbam** [comment]
Thank you @jphorn , I have added it to the code!
