### ISSUE TITLE
Safari reader compatibilty

### ISSUE THREAD

**Issue by stayallive** [level-level/ll-cookie-wall#27]
Hey Guys,

I have 1 more bigger PR lined up but I wanted to check in if this is something that you want to include.

In our use (at iculture.nl) of the cookie wall we come across a lot of readers using Safari reader on their macs and iOS devices. However in this mode the accept / read more links are not clickable and are shown in plain text, also the text in the read more section not visible at all.

For the accept button to work we have changed from a form that posts to a simple link that makes a GET request with an added url parameter to indicate the user has accepted. This also makes the wall a bit more "no javascript" friendly as a side effect.

We have figured out a way to make this "read more" text visible with some "clever" found CSS tricks and class names (combining lots of bits found on the web) making the functionality look the same but the full read more text visible in the reader mode.

Both these things work very well for us, is this something you guys would like to accept?

**Comment by jmslbam** [comment]
Hi @stayallive , sorry this one skipped my attention... one year... 😅
I don't know if you still want to send the PR, but we haven't touch this plugin for a long time. Although you enhancements sound fine I remember the reason why we implemented this JS solution, is to prevent an extra hit (PHP) to the server by setting the cookie via JS.

Also reworking the form to a GET will break backwards-compatibility right? I can put a link to your Fork in the readme if somebody needs a more enhanced version.
